name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create local.properties
      run: echo "TELEGRAM_API_ID=$TELEGRAM_API_ID\nTELEGRAM_API_HASH=$TELEGRAM_API_HASH" > local.properties
    - name: Build with Gradle
      run: ./gradlew build
